/**
 * Audit-action catalog (blueprint Appendix B). Sensitive mutations write an
 * AuditLog row with one of these stable action constants (old->new values, reason).
 * Grows per milestone.
 */
export const AuditActions = {
  // admissions / students / enrollment (M2)
  INQUIRY_STATUS_CHANGED: 'INQUIRY_STATUS_CHANGED',
  STUDENT_ADMITTED: 'STUDENT_ADMITTED',
  STUDENT_UPDATED: 'STUDENT_UPDATED',
  STUDENT_DELETED: 'STUDENT_DELETED',
  STUDENT_STATUS_CHANGED: 'STUDENT_STATUS_CHANGED',
  GUARDIAN_LINKED: 'GUARDIAN_LINKED',
  GUARDIAN_UNLINKED: 'GUARDIAN_UNLINKED',
  PRIMARY_GUARDIAN_CHANGED: 'PRIMARY_GUARDIAN_CHANGED',
  ENROLLMENT_TRANSFERRED: 'ENROLLMENT_TRANSFERRED',
  ACADEMIC_YEAR_SET_CURRENT: 'ACADEMIC_YEAR_SET_CURRENT',

  // Structural deletes (setup). audit_logs has no FK to the entity — by design, so the row
  // outlives what it describes — which means oldValue must carry enough identity to say
  // WHAT was destroyed, not just its now-dangling id.
  CAMPUS_DELETED: 'CAMPUS_DELETED',
  CLASS_DELETED: 'CLASS_DELETED',
  SECTION_DELETED: 'SECTION_DELETED',
  SUBJECT_DELETED: 'SUBJECT_DELETED',
  TEACHER_ASSIGNMENT_REMOVED: 'TEACHER_ASSIGNMENT_REMOVED',

  // auth / platform (M1)
  ROLE_CHANGED: 'ROLE_CHANGED',
  USER_DISABLED: 'USER_DISABLED',
  USER_REMOVED: 'USER_REMOVED',
  MFA_RESET: 'MFA_RESET',
  SCHOOL_PROVISIONED: 'SCHOOL_PROVISIONED',

  // finance / exams (later milestones — declared as they are used)
  FEE_WAIVED: 'FEE_WAIVED',
  FINE_WAIVED: 'FINE_WAIVED',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  GRADE_CHANGED_POST_PUBLISH: 'GRADE_CHANGED_POST_PUBLISH',
  TERM_DELETED: 'TERM_DELETED',
  ATTENDANCE_EDITED_POST_WINDOW: 'ATTENDANCE_EDITED_POST_WINDOW',
  DISCOUNT_APPROVED: 'DISCOUNT_APPROVED',
  DISCOUNT_REVOKED: 'DISCOUNT_REVOKED',
  PROMOTION_OVERRIDE: 'PROMOTION_OVERRIDE',
  WITHDRAWAL_FEE_OVERRIDE: 'WITHDRAWAL_FEE_OVERRIDE',
  PII_ANONYMIZED: 'PII_ANONYMIZED',
  DATA_EXPORTED: 'DATA_EXPORTED',
  SUPPORT_SESSION_STARTED: 'SUPPORT_SESSION_STARTED',

  // HR — recruitment
  VACANCY_CREATED: 'VACANCY_CREATED',
  VACANCY_CLOSED: 'VACANCY_CLOSED',
  TEACHER_APPLICATION_CREATED: 'TEACHER_APPLICATION_CREATED',
  TEACHER_APPLICATION_STATUS_CHANGED: 'TEACHER_APPLICATION_STATUS_CHANGED',
  TEACHER_APPLICATION_HIRED: 'TEACHER_APPLICATION_HIRED',

  // Access grants — owner assigns/removes a role on an existing employee (reused account)
  HR_ACCESS_GRANTED: 'HR_ACCESS_GRANTED',
  HR_ACCESS_REVOKED: 'HR_ACCESS_REVOKED',
  CAMPUS_ADMIN_GRANTED: 'CAMPUS_ADMIN_GRANTED',
  CAMPUS_ADMIN_REVOKED: 'CAMPUS_ADMIN_REVOKED',
  ROLE_ACCESS_GRANTED: 'ROLE_ACCESS_GRANTED',
  ROLE_ACCESS_REVOKED: 'ROLE_ACCESS_REVOKED',
  MODULE_ACCESS_CHANGED: 'MODULE_ACCESS_CHANGED',
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
