#!/usr/bin/env bash
# Generate a .env for the FREE TEST deployment (brain: Free Live Test Deployment Plan).
#
# Every secret below is generated FRESH on each run. Nothing is copied from .env.example, because
# those values are public: the repo, and the brain, both contain them.
#
# ⚠️ ENCRYPTION_MASTER_KEY is not cosmetic — student CNICs are stored encrypted under it. Rotating it
# on an existing database makes previously-encrypted fields undecryptable. Generate ONCE per
# environment; this script refuses to clobber an existing .env for exactly that reason.
#
# Usage:  ./deploy/bootstrap-test-env.sh <apex-domain>
#   e.g.  ./deploy/bootstrap-test-env.sh 140-245-39-243.sslip.io
set -euo pipefail

APEX="${1:?usage: bootstrap-test-env.sh <apex-domain>}"
OUT="$(dirname "$0")/../.env"

if [ -f "$OUT" ]; then
  echo "refusing to overwrite existing .env (ENCRYPTION_MASTER_KEY rotation would orphan encrypted data)" >&2
  echo "move it aside deliberately if that is really what you want" >&2
  exit 1
fi

rnd() { openssl rand -base64 "${1:-32}" | tr -d '\n=' | tr '+/' '-_'; }

# ⚠️ Computed OUT HERE, not inside the heredoc below. The heredoc is unquoted (it has to be, to
# interpolate), so a backslash written inside it is eaten by the shell before sed sees it and the
# dots come out unescaped — which silently turns the Caddy host_regexp into a near-miss matcher.
# A literal backslash via its own variable. Writing the escape inline instead --- \. or a sed
# expression --- is eaten by one shell layer or another before it lands, and the failure is silent:
# unescaped dots still match, just too much, so the Caddy host_regexp quietly becomes a near-miss.
BS=''
APEX_REGEX="${APEX//./${BS}.}"

PG_APP_PW="$(rnd 24)"
PG_PLATFORM_PW="$(rnd 24)"
PG_SUPER_PW="$(rnd 24)"
MINIO_PW="$(rnd 24)"

cat > "$OUT" <<EOF
# GENERATED by deploy/bootstrap-test-env.sh for the disposable test deployment. Do not commit.
NODE_ENV=production
API_PORT=4000
APP_APEX_DOMAIN=${APEX}
# Role labels must never resolve as a school (blueprint 21.1).
RESERVED_SUBDOMAINS=www,api,admin,app,superadmin,owner,staff,student,s3

# ── Database: three roles, three privilege levels ─────────────
# app_user carries the request path and MUST NOT have BYPASSRLS.
DATABASE_URL=postgresql://app_user:${PG_APP_PW}@postgres:5432/school?schema=public
PLATFORM_DATABASE_URL=postgresql://platform_admin:${PG_PLATFORM_PW}@postgres:5432/school?schema=public
MIGRATION_DATABASE_URL=postgresql://postgres:${PG_SUPER_PW}@postgres:5432/school?schema=public
POSTGRES_PASSWORD=${PG_SUPER_PW}
APP_USER_PASSWORD=${PG_APP_PW}
PLATFORM_USER_PASSWORD=${PG_PLATFORM_PW}

REDIS_URL=redis://redis:6379

# ── Auth ──────────────────────────────────────────────────────
JWT_ACTIVE_KID=k1
JWT_KEYS={"k1":"$(rnd 32)","k2":"$(rnd 32)"}
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=30d
COOKIE_SECURE=true
COOKIE_DOMAIN=${APEX}

# ── Field-level encryption — generate ONCE, never rotate in place ──
ENCRYPTION_MASTER_KEY=$(openssl rand -base64 32)

# ── Object storage: in-cluster MinIO (no R2 signup needed for a test) ──
# S3_ENDPOINT is how the API reaches storage; S3_PUBLIC_ENDPOINT is how the BROWSER does.
# ⚠️ They must differ when storage is self-hosted: uploads/downloads are presigned and go
# browser → storage directly, and a URL signed for the container name `minio` resolves nowhere
# outside docker (and would be blocked as mixed content from an HTTPS page besides).
S3_ENDPOINT=http://minio:9000
S3_PUBLIC_ENDPOINT=https://s3.${APEX}
S3_REGION=us-east-1
S3_BUCKET=school-uploads
S3_ACCESS_KEY_ID=schoolworks
S3_SECRET_ACCESS_KEY=${MINIO_PW}
S3_FORCE_PATH_STYLE=true
MINIO_ROOT_USER=schoolworks
MINIO_ROOT_PASSWORD=${MINIO_PW}

# No arm64/amd64 scan container in this topology; uploads are accepted UNSCANNED.
CLAMAV_ENABLED=false
CLAMAV_HOST=clamav
CLAMAV_PORT=3310

SMS_PROVIDER=console
SMS_API_KEY=
SMS_SENDER_ID=
SMS_WEBHOOK_HMAC_SECRET=$(rnd 24)

SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
LEAD_NOTIFY_EMAIL=

LOG_LEVEL=info
SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0

# The only thing between the login door and the open internet. Keep it on.
RATE_LIMIT_ENABLED=true

# Consumed by deploy/Caddyfile.sslip. APEX_REGEX is the apex with dots escaped.
APEX_DOMAIN=${APEX}
APEX_REGEX=${APEX_REGEX}
EOF

chmod 600 "$OUT"
echo "wrote $OUT (mode 600) for apex ${APEX}"
echo "secrets are fresh; nothing came from .env.example"
