/**
 * Stable machine error codes (blueprint Appendix A). Published in OpenAPI; the
 * frontend switches on these, never on message text. Add codes here as features land.
 */
export const ErrorCodes = {
  // tenant / auth
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_VIOLATION: 'TENANT_VIOLATION',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  /** A mandatory-MFA role reached a sensitive route without enrolling. Distinct from FORBIDDEN so the
   *  client can send the person to Security instead of saying they lack permission. */
  MFA_ENROLMENT_REQUIRED: 'MFA_ENROLMENT_REQUIRED',
  REFRESH_INVALID: 'REFRESH_INVALID',
  CSRF_INVALID: 'CSRF_INVALID',

  // domain (seed set — grows per milestone)
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  ATTENDANCE_CONFLICT: 'ATTENDANCE_CONFLICT',
  ATTENDANCE_LOCKED: 'ATTENDANCE_LOCKED',
  RESULTS_INCOMPLETE: 'RESULTS_INCOMPLETE',
  WEIGHTAGE_SUM_INVALID: 'WEIGHTAGE_SUM_INVALID',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  OVERPAYMENT_USE_ADVANCE: 'OVERPAYMENT_USE_ADVANCE',
  SECTION_FULL: 'SECTION_FULL',
  GR_NUMBER_TAKEN: 'GR_NUMBER_TAKEN',
  ROLL_NUMBER_TAKEN: 'ROLL_NUMBER_TAKEN',
  AGE_OUT_OF_RANGE: 'AGE_OUT_OF_RANGE',
  LEAVE_OVERLAP: 'LEAVE_OVERLAP',
  INSUFFICIENT_SMS_CREDITS: 'INSUFFICIENT_SMS_CREDITS',
  PHONE_UNVERIFIED: 'PHONE_UNVERIFIED',
  SMS_OPTED_OUT: 'SMS_OPTED_OUT',
  SELF_PAYMENT_FORBIDDEN: 'SELF_PAYMENT_FORBIDDEN',
  FILE_INFECTED: 'FILE_INFECTED',
  VIRUS_SCAN_UNAVAILABLE: 'VIRUS_SCAN_UNAVAILABLE',

  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  /** A route that exists as a deliberate seam but is not wired up — refuses rather than half-works. */
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
